name: Build application

on: [push, pull_request]

jobs:
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    env:
        CC: clang-9
        CXX: clang++-9
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install clang-9
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake CMAKE_BUILD_TYPE=RELEASE .. -DBUILD_GMOCK=OFF
        make -j4
        cd ..
    - name: Run tests
      run: |
        cd build/bin
        ./Tests
  windows-msvc-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Build
      run: |
        mkdir build_dir
        cd build_dir
        cmake CMAKE_BUILD_TYPE=RELEASE .. -DBUILD_GMOCK=OFF
        cd .. 
        cmake --build build_dir
    - name: Run tests
      run: |
        cd build_dir/bin
        ./Tests.exe
